server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.50.132
      port: 6379
      username: root
      password: panzifeng0922
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          max-wait: 100ms
          time-between-eviction-runs: 10s
  mvc:
    view:
      prefix: /templates/
      suffix: .html
short-link:
  statistic:
    location:
      user-key:
        435a1b631a2584625a577ebfcdb2ccca
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml